// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module AES_En_De_AES_En_De_Pipeline_VITIS_LOOP_620_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_TVALID,
        output_stream_TREADY,
        En_Decryption,
        num_blocks,
        add_ln655,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TLAST,
        input_stream_TDATA,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        w_0,
        w_1,
        w_2,
        w_3,
        w_4,
        w_5,
        w_6,
        w_7,
        w_8,
        w_9,
        w_10,
        w_11,
        w_12,
        w_13,
        w_14,
        w_15,
        w_16,
        w_17,
        w_18,
        w_19,
        w_20,
        w_21,
        w_22,
        w_23,
        w_24,
        w_25,
        w_26,
        w_27,
        w_28,
        w_29,
        w_30,
        w_31,
        w_32,
        w_33,
        w_34,
        w_35,
        w_36,
        w_37,
        w_38,
        w_39,
        w_40,
        w_41,
        w_42,
        w_43
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input_stream_TVALID;
input   output_stream_TREADY;
input  [31:0] En_Decryption;
input  [27:0] num_blocks;
input  [28:0] add_ln655;
output  [127:0] output_stream_TDATA;
output   output_stream_TVALID;
output  [15:0] output_stream_TKEEP;
output  [15:0] output_stream_TSTRB;
output  [0:0] output_stream_TLAST;
input  [127:0] input_stream_TDATA;
output   input_stream_TREADY;
input  [15:0] input_stream_TKEEP;
input  [15:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
input  [31:0] w_0;
input  [31:0] w_1;
input  [31:0] w_2;
input  [31:0] w_3;
input  [31:0] w_4;
input  [31:0] w_5;
input  [31:0] w_6;
input  [31:0] w_7;
input  [31:0] w_8;
input  [31:0] w_9;
input  [31:0] w_10;
input  [31:0] w_11;
input  [31:0] w_12;
input  [31:0] w_13;
input  [31:0] w_14;
input  [31:0] w_15;
input  [31:0] w_16;
input  [31:0] w_17;
input  [31:0] w_18;
input  [31:0] w_19;
input  [31:0] w_20;
input  [31:0] w_21;
input  [31:0] w_22;
input  [31:0] w_23;
input  [31:0] w_24;
input  [31:0] w_25;
input  [31:0] w_26;
input  [31:0] w_27;
input  [31:0] w_28;
input  [31:0] w_29;
input  [31:0] w_30;
input  [31:0] w_31;
input  [31:0] w_32;
input  [31:0] w_33;
input  [31:0] w_34;
input  [31:0] w_35;
input  [31:0] w_36;
input  [31:0] w_37;
input  [31:0] w_38;
input  [31:0] w_39;
input  [31:0] w_40;
input  [31:0] w_41;
input  [31:0] w_42;
input  [31:0] w_43;

reg ap_idle;
reg output_stream_TVALID;
reg input_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln620_reg_1109;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state23_pp0_stage0_iter22;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln620_fu_688_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    output_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    input_stream_TDATA_blk_n;
reg   [7:0] block_data_15_0_reg_286;
reg   [7:0] block_data_14_0_reg_296;
reg   [7:0] block_data_13_0_reg_306;
reg   [7:0] block_data_12_0_reg_316;
reg   [7:0] block_data_11_0_reg_326;
reg   [7:0] block_data_10_0_reg_336;
reg   [7:0] block_data_9_0_reg_346;
reg   [7:0] block_data_8_0_reg_356;
reg   [7:0] block_data_7_0_reg_366;
reg   [7:0] block_data_6_0_reg_376;
reg   [7:0] block_data_5_0_reg_386;
reg   [7:0] block_data_4_0_reg_396;
reg   [7:0] block_data_3_0_reg_406;
reg   [7:0] block_data_2_0_reg_416;
reg   [7:0] block_data_1_0_reg_426;
reg   [7:0] block_data_0_reg_436;
wire   [0:0] icmp_ln636_fu_666_p2;
reg   [0:0] icmp_ln636_reg_1105;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter1_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter2_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter3_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter4_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter5_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter6_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter7_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter8_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter9_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter10_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter11_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter12_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter13_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter14_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter15_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter16_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter17_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter18_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter19_reg;
reg   [0:0] icmp_ln620_reg_1109_pp0_iter20_reg;
wire   [0:0] icmp_ln655_fu_700_p2;
reg   [0:0] icmp_ln655_reg_1113;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter1_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter2_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter3_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter4_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter5_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter6_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter7_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter8_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter9_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter10_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter11_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter12_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter13_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter14_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter15_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter16_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter17_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter18_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter19_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter20_reg;
reg   [0:0] icmp_ln655_reg_1113_pp0_iter21_reg;
wire   [7:0] block_data_fu_715_p1;
wire   [7:0] grp_deAes_return_fu_446_c_1_read;
wire   [7:0] grp_deAes_return_fu_446_c_2_read;
wire   [7:0] grp_deAes_return_fu_446_c_3_read;
wire   [7:0] grp_deAes_return_fu_446_c_4_read;
wire   [7:0] grp_deAes_return_fu_446_c_5_read;
wire   [7:0] grp_deAes_return_fu_446_c_6_read;
wire   [7:0] grp_deAes_return_fu_446_c_7_read;
wire   [7:0] grp_deAes_return_fu_446_c_8_read;
wire   [7:0] grp_deAes_return_fu_446_c_9_read;
wire   [7:0] grp_deAes_return_fu_446_c_10_read;
wire   [7:0] grp_deAes_return_fu_446_c_11_read;
wire   [7:0] grp_deAes_return_fu_446_c_1213_read;
wire   [7:0] grp_deAes_return_fu_446_c_13_read;
wire   [7:0] grp_deAes_return_fu_446_c_14_read;
wire   [7:0] grp_deAes_return_fu_446_c_15_read;
wire   [7:0] grp_deAes_return_fu_446_ap_return_0;
wire   [7:0] grp_deAes_return_fu_446_ap_return_1;
wire   [7:0] grp_deAes_return_fu_446_ap_return_2;
wire   [7:0] grp_deAes_return_fu_446_ap_return_3;
wire   [7:0] grp_deAes_return_fu_446_ap_return_4;
wire   [7:0] grp_deAes_return_fu_446_ap_return_5;
wire   [7:0] grp_deAes_return_fu_446_ap_return_6;
wire   [7:0] grp_deAes_return_fu_446_ap_return_7;
wire   [7:0] grp_deAes_return_fu_446_ap_return_8;
wire   [7:0] grp_deAes_return_fu_446_ap_return_9;
wire   [7:0] grp_deAes_return_fu_446_ap_return_10;
wire   [7:0] grp_deAes_return_fu_446_ap_return_11;
wire   [7:0] grp_deAes_return_fu_446_ap_return_12;
wire   [7:0] grp_deAes_return_fu_446_ap_return_13;
wire   [7:0] grp_deAes_return_fu_446_ap_return_14;
wire   [7:0] grp_deAes_return_fu_446_ap_return_15;
reg    grp_deAes_return_fu_446_ap_ce;
reg    ap_predicate_op67_call_state2;
reg    ap_predicate_op71_call_state3;
reg    ap_predicate_op75_call_state5;
reg    ap_predicate_op79_call_state7;
reg    ap_predicate_op83_call_state9;
reg    ap_predicate_op87_call_state11;
reg    ap_predicate_op91_call_state13;
reg    ap_predicate_op95_call_state15;
reg    ap_predicate_op99_call_state17;
reg    ap_predicate_op103_call_state19;
reg    ap_predicate_op107_call_state21;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call0;
reg    ap_block_state23_pp0_stage0_iter22_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp67;
wire   [7:0] grp_aes_return_fu_556_p_1_read;
wire   [7:0] grp_aes_return_fu_556_p_2_read;
wire   [7:0] grp_aes_return_fu_556_p_3_read;
wire   [7:0] grp_aes_return_fu_556_p_4_read;
wire   [7:0] grp_aes_return_fu_556_p_5_read;
wire   [7:0] grp_aes_return_fu_556_p_6_read;
wire   [7:0] grp_aes_return_fu_556_p_7_read;
wire   [7:0] grp_aes_return_fu_556_p_8_read;
wire   [7:0] grp_aes_return_fu_556_p_9_read;
wire   [7:0] grp_aes_return_fu_556_p_10_read;
wire   [7:0] grp_aes_return_fu_556_p_11_read;
wire   [7:0] grp_aes_return_fu_556_p_1213_read;
wire   [7:0] grp_aes_return_fu_556_p_13_read;
wire   [7:0] grp_aes_return_fu_556_p_14_read;
wire   [7:0] grp_aes_return_fu_556_p_15_read;
wire   [7:0] grp_aes_return_fu_556_ap_return_0;
wire   [7:0] grp_aes_return_fu_556_ap_return_1;
wire   [7:0] grp_aes_return_fu_556_ap_return_2;
wire   [7:0] grp_aes_return_fu_556_ap_return_3;
wire   [7:0] grp_aes_return_fu_556_ap_return_4;
wire   [7:0] grp_aes_return_fu_556_ap_return_5;
wire   [7:0] grp_aes_return_fu_556_ap_return_6;
wire   [7:0] grp_aes_return_fu_556_ap_return_7;
wire   [7:0] grp_aes_return_fu_556_ap_return_8;
wire   [7:0] grp_aes_return_fu_556_ap_return_9;
wire   [7:0] grp_aes_return_fu_556_ap_return_10;
wire   [7:0] grp_aes_return_fu_556_ap_return_11;
wire   [7:0] grp_aes_return_fu_556_ap_return_12;
wire   [7:0] grp_aes_return_fu_556_ap_return_13;
wire   [7:0] grp_aes_return_fu_556_ap_return_14;
wire   [7:0] grp_aes_return_fu_556_ap_return_15;
reg    grp_aes_return_fu_556_ap_ce;
reg    ap_predicate_op69_call_state2;
reg    ap_predicate_op72_call_state3;
reg    ap_predicate_op76_call_state5;
reg    ap_predicate_op80_call_state7;
reg    ap_predicate_op84_call_state9;
reg    ap_predicate_op88_call_state11;
reg    ap_predicate_op92_call_state13;
reg    ap_predicate_op96_call_state15;
reg    ap_predicate_op100_call_state17;
reg    ap_predicate_op104_call_state19;
reg    ap_predicate_op108_call_state21;
reg    ap_block_pp0_stage0_11001_ignoreCallOp69;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_15_0_reg_286;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_14_0_reg_296;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_13_0_reg_306;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_12_0_reg_316;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_11_0_reg_326;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_10_0_reg_336;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_9_0_reg_346;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_8_0_reg_356;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_7_0_reg_366;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_6_0_reg_376;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_5_0_reg_386;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_4_0_reg_396;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_3_0_reg_406;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_2_0_reg_416;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_1_0_reg_426;
wire   [7:0] ap_phi_reg_pp0_iter21_block_data_0_reg_436;
wire    ap_block_pp0_stage0_ignoreCallOp67;
wire    ap_block_pp0_stage0_ignoreCallOp71;
wire    ap_block_pp0_stage0_ignoreCallOp75;
wire    ap_block_pp0_stage0_ignoreCallOp79;
wire    ap_block_pp0_stage0_ignoreCallOp83;
wire    ap_block_pp0_stage0_ignoreCallOp87;
wire    ap_block_pp0_stage0_ignoreCallOp91;
wire    ap_block_pp0_stage0_ignoreCallOp95;
wire    ap_block_pp0_stage0_ignoreCallOp99;
wire    ap_block_pp0_stage0_ignoreCallOp103;
wire    ap_block_pp0_stage0_ignoreCallOp107;
wire    ap_block_pp0_stage0_ignoreCallOp69;
wire    ap_block_pp0_stage0_ignoreCallOp72;
wire    ap_block_pp0_stage0_ignoreCallOp76;
wire    ap_block_pp0_stage0_ignoreCallOp80;
wire    ap_block_pp0_stage0_ignoreCallOp84;
wire    ap_block_pp0_stage0_ignoreCallOp88;
wire    ap_block_pp0_stage0_ignoreCallOp92;
wire    ap_block_pp0_stage0_ignoreCallOp96;
wire    ap_block_pp0_stage0_ignoreCallOp100;
wire    ap_block_pp0_stage0_ignoreCallOp104;
wire    ap_block_pp0_stage0_ignoreCallOp108;
reg   [26:0] block_fu_234;
wire   [26:0] block_2_fu_694_p2;
wire    ap_loop_init;
reg   [26:0] ap_sig_allocacmp_block_1;
reg    ap_block_pp0_stage0_01001;
wire   [27:0] zext_ln620_1_fu_684_p1;
wire   [28:0] zext_ln620_fu_680_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 block_fu_234 = 27'd0;
#0 ap_done_reg = 1'b0;
end

AES_En_De_deAes_return grp_deAes_return_fu_446(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .c_0_read(block_data_fu_715_p1),
    .c_1_read(grp_deAes_return_fu_446_c_1_read),
    .c_2_read(grp_deAes_return_fu_446_c_2_read),
    .c_3_read(grp_deAes_return_fu_446_c_3_read),
    .c_4_read(grp_deAes_return_fu_446_c_4_read),
    .c_5_read(grp_deAes_return_fu_446_c_5_read),
    .c_6_read(grp_deAes_return_fu_446_c_6_read),
    .c_7_read(grp_deAes_return_fu_446_c_7_read),
    .c_8_read(grp_deAes_return_fu_446_c_8_read),
    .c_9_read(grp_deAes_return_fu_446_c_9_read),
    .c_10_read(grp_deAes_return_fu_446_c_10_read),
    .c_11_read(grp_deAes_return_fu_446_c_11_read),
    .c_1213_read(grp_deAes_return_fu_446_c_1213_read),
    .c_13_read(grp_deAes_return_fu_446_c_13_read),
    .c_14_read(grp_deAes_return_fu_446_c_14_read),
    .c_15_read(grp_deAes_return_fu_446_c_15_read),
    .w_40(w_40),
    .w_41(w_41),
    .w_42(w_42),
    .w_43(w_43),
    .w_36(w_36),
    .w_37(w_37),
    .w_38(w_38),
    .w_39(w_39),
    .w_32(w_32),
    .w_33(w_33),
    .w_34(w_34),
    .w_35(w_35),
    .w_28(w_28),
    .w_29(w_29),
    .w_30(w_30),
    .w_31(w_31),
    .w_24(w_24),
    .w_25(w_25),
    .w_26(w_26),
    .w_27(w_27),
    .w_20(w_20),
    .w_21(w_21),
    .w_22(w_22),
    .w_23(w_23),
    .w_16(w_16),
    .w_17(w_17),
    .w_18(w_18),
    .w_19(w_19),
    .w_12(w_12),
    .w_13(w_13),
    .w_14(w_14),
    .w_15(w_15),
    .w_8(w_8),
    .w_9(w_9),
    .w_10(w_10),
    .w_11(w_11),
    .w_4(w_4),
    .w_5(w_5),
    .w_6(w_6),
    .w_7(w_7),
    .w_0(w_0),
    .w_1(w_1),
    .w_2(w_2),
    .w_3(w_3),
    .ap_return_0(grp_deAes_return_fu_446_ap_return_0),
    .ap_return_1(grp_deAes_return_fu_446_ap_return_1),
    .ap_return_2(grp_deAes_return_fu_446_ap_return_2),
    .ap_return_3(grp_deAes_return_fu_446_ap_return_3),
    .ap_return_4(grp_deAes_return_fu_446_ap_return_4),
    .ap_return_5(grp_deAes_return_fu_446_ap_return_5),
    .ap_return_6(grp_deAes_return_fu_446_ap_return_6),
    .ap_return_7(grp_deAes_return_fu_446_ap_return_7),
    .ap_return_8(grp_deAes_return_fu_446_ap_return_8),
    .ap_return_9(grp_deAes_return_fu_446_ap_return_9),
    .ap_return_10(grp_deAes_return_fu_446_ap_return_10),
    .ap_return_11(grp_deAes_return_fu_446_ap_return_11),
    .ap_return_12(grp_deAes_return_fu_446_ap_return_12),
    .ap_return_13(grp_deAes_return_fu_446_ap_return_13),
    .ap_return_14(grp_deAes_return_fu_446_ap_return_14),
    .ap_return_15(grp_deAes_return_fu_446_ap_return_15),
    .ap_ce(grp_deAes_return_fu_446_ap_ce)
);

AES_En_De_aes_return grp_aes_return_fu_556(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_0_read(block_data_fu_715_p1),
    .p_1_read(grp_aes_return_fu_556_p_1_read),
    .p_2_read(grp_aes_return_fu_556_p_2_read),
    .p_3_read(grp_aes_return_fu_556_p_3_read),
    .p_4_read(grp_aes_return_fu_556_p_4_read),
    .p_5_read(grp_aes_return_fu_556_p_5_read),
    .p_6_read(grp_aes_return_fu_556_p_6_read),
    .p_7_read(grp_aes_return_fu_556_p_7_read),
    .p_8_read(grp_aes_return_fu_556_p_8_read),
    .p_9_read(grp_aes_return_fu_556_p_9_read),
    .p_10_read(grp_aes_return_fu_556_p_10_read),
    .p_11_read(grp_aes_return_fu_556_p_11_read),
    .p_1213_read(grp_aes_return_fu_556_p_1213_read),
    .p_13_read(grp_aes_return_fu_556_p_13_read),
    .p_14_read(grp_aes_return_fu_556_p_14_read),
    .p_15_read(grp_aes_return_fu_556_p_15_read),
    .w_0(w_0),
    .w_1(w_1),
    .w_2(w_2),
    .w_3(w_3),
    .w_4(w_4),
    .w_5(w_5),
    .w_6(w_6),
    .w_7(w_7),
    .w_8(w_8),
    .w_9(w_9),
    .w_10(w_10),
    .w_11(w_11),
    .w_12(w_12),
    .w_13(w_13),
    .w_14(w_14),
    .w_15(w_15),
    .w_16(w_16),
    .w_17(w_17),
    .w_18(w_18),
    .w_19(w_19),
    .w_20(w_20),
    .w_21(w_21),
    .w_22(w_22),
    .w_23(w_23),
    .w_24(w_24),
    .w_25(w_25),
    .w_26(w_26),
    .w_27(w_27),
    .w_28(w_28),
    .w_29(w_29),
    .w_30(w_30),
    .w_31(w_31),
    .w_32(w_32),
    .w_33(w_33),
    .w_34(w_34),
    .w_35(w_35),
    .w_36(w_36),
    .w_37(w_37),
    .w_38(w_38),
    .w_39(w_39),
    .w_40(w_40),
    .w_41(w_41),
    .w_42(w_42),
    .w_43(w_43),
    .ap_return_0(grp_aes_return_fu_556_ap_return_0),
    .ap_return_1(grp_aes_return_fu_556_ap_return_1),
    .ap_return_2(grp_aes_return_fu_556_ap_return_2),
    .ap_return_3(grp_aes_return_fu_556_ap_return_3),
    .ap_return_4(grp_aes_return_fu_556_ap_return_4),
    .ap_return_5(grp_aes_return_fu_556_ap_return_5),
    .ap_return_6(grp_aes_return_fu_556_ap_return_6),
    .ap_return_7(grp_aes_return_fu_556_ap_return_7),
    .ap_return_8(grp_aes_return_fu_556_ap_return_8),
    .ap_return_9(grp_aes_return_fu_556_ap_return_9),
    .ap_return_10(grp_aes_return_fu_556_ap_return_10),
    .ap_return_11(grp_aes_return_fu_556_ap_return_11),
    .ap_return_12(grp_aes_return_fu_556_ap_return_12),
    .ap_return_13(grp_aes_return_fu_556_ap_return_13),
    .ap_return_14(grp_aes_return_fu_556_ap_return_14),
    .ap_return_15(grp_aes_return_fu_556_ap_return_15),
    .ap_ce(grp_aes_return_fu_556_ap_ce)
);

AES_En_De_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter21_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_0_reg_436 <= grp_deAes_return_fu_446_ap_return_0;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_0_reg_436 <= grp_aes_return_fu_556_ap_return_0;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_0_reg_436 <= ap_phi_reg_pp0_iter21_block_data_0_reg_436;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_10_0_reg_336 <= grp_deAes_return_fu_446_ap_return_10;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_10_0_reg_336 <= grp_aes_return_fu_556_ap_return_10;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_10_0_reg_336 <= ap_phi_reg_pp0_iter21_block_data_10_0_reg_336;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_11_0_reg_326 <= grp_deAes_return_fu_446_ap_return_11;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_11_0_reg_326 <= grp_aes_return_fu_556_ap_return_11;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_11_0_reg_326 <= ap_phi_reg_pp0_iter21_block_data_11_0_reg_326;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_12_0_reg_316 <= grp_deAes_return_fu_446_ap_return_12;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_12_0_reg_316 <= grp_aes_return_fu_556_ap_return_12;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_12_0_reg_316 <= ap_phi_reg_pp0_iter21_block_data_12_0_reg_316;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_13_0_reg_306 <= grp_deAes_return_fu_446_ap_return_13;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_13_0_reg_306 <= grp_aes_return_fu_556_ap_return_13;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_13_0_reg_306 <= ap_phi_reg_pp0_iter21_block_data_13_0_reg_306;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_14_0_reg_296 <= grp_deAes_return_fu_446_ap_return_14;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_14_0_reg_296 <= grp_aes_return_fu_556_ap_return_14;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_14_0_reg_296 <= ap_phi_reg_pp0_iter21_block_data_14_0_reg_296;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_15_0_reg_286 <= grp_deAes_return_fu_446_ap_return_15;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_15_0_reg_286 <= grp_aes_return_fu_556_ap_return_15;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_15_0_reg_286 <= ap_phi_reg_pp0_iter21_block_data_15_0_reg_286;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_1_0_reg_426 <= grp_deAes_return_fu_446_ap_return_1;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_1_0_reg_426 <= grp_aes_return_fu_556_ap_return_1;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_1_0_reg_426 <= ap_phi_reg_pp0_iter21_block_data_1_0_reg_426;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_2_0_reg_416 <= grp_deAes_return_fu_446_ap_return_2;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_2_0_reg_416 <= grp_aes_return_fu_556_ap_return_2;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_2_0_reg_416 <= ap_phi_reg_pp0_iter21_block_data_2_0_reg_416;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_3_0_reg_406 <= grp_deAes_return_fu_446_ap_return_3;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_3_0_reg_406 <= grp_aes_return_fu_556_ap_return_3;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_3_0_reg_406 <= ap_phi_reg_pp0_iter21_block_data_3_0_reg_406;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_4_0_reg_396 <= grp_deAes_return_fu_446_ap_return_4;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_4_0_reg_396 <= grp_aes_return_fu_556_ap_return_4;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_4_0_reg_396 <= ap_phi_reg_pp0_iter21_block_data_4_0_reg_396;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_5_0_reg_386 <= grp_deAes_return_fu_446_ap_return_5;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_5_0_reg_386 <= grp_aes_return_fu_556_ap_return_5;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_5_0_reg_386 <= ap_phi_reg_pp0_iter21_block_data_5_0_reg_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_6_0_reg_376 <= grp_deAes_return_fu_446_ap_return_6;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_6_0_reg_376 <= grp_aes_return_fu_556_ap_return_6;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_6_0_reg_376 <= ap_phi_reg_pp0_iter21_block_data_6_0_reg_376;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_7_0_reg_366 <= grp_deAes_return_fu_446_ap_return_7;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_7_0_reg_366 <= grp_aes_return_fu_556_ap_return_7;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_7_0_reg_366 <= ap_phi_reg_pp0_iter21_block_data_7_0_reg_366;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_8_0_reg_356 <= grp_deAes_return_fu_446_ap_return_8;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_8_0_reg_356 <= grp_aes_return_fu_556_ap_return_8;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_8_0_reg_356 <= ap_phi_reg_pp0_iter21_block_data_8_0_reg_356;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0))) begin
            block_data_9_0_reg_346 <= grp_deAes_return_fu_446_ap_return_9;
        end else if (((icmp_ln620_reg_1109_pp0_iter20_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1))) begin
            block_data_9_0_reg_346 <= grp_aes_return_fu_556_ap_return_9;
        end else if (~(icmp_ln620_reg_1109_pp0_iter20_reg == 1'd0)) begin
            block_data_9_0_reg_346 <= ap_phi_reg_pp0_iter21_block_data_9_0_reg_346;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln620_fu_688_p2 == 1'd1))) begin
            block_fu_234 <= block_2_fu_694_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            block_fu_234 <= 27'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln620_reg_1109_pp0_iter10_reg <= icmp_ln620_reg_1109_pp0_iter9_reg;
        icmp_ln620_reg_1109_pp0_iter11_reg <= icmp_ln620_reg_1109_pp0_iter10_reg;
        icmp_ln620_reg_1109_pp0_iter12_reg <= icmp_ln620_reg_1109_pp0_iter11_reg;
        icmp_ln620_reg_1109_pp0_iter13_reg <= icmp_ln620_reg_1109_pp0_iter12_reg;
        icmp_ln620_reg_1109_pp0_iter14_reg <= icmp_ln620_reg_1109_pp0_iter13_reg;
        icmp_ln620_reg_1109_pp0_iter15_reg <= icmp_ln620_reg_1109_pp0_iter14_reg;
        icmp_ln620_reg_1109_pp0_iter16_reg <= icmp_ln620_reg_1109_pp0_iter15_reg;
        icmp_ln620_reg_1109_pp0_iter17_reg <= icmp_ln620_reg_1109_pp0_iter16_reg;
        icmp_ln620_reg_1109_pp0_iter18_reg <= icmp_ln620_reg_1109_pp0_iter17_reg;
        icmp_ln620_reg_1109_pp0_iter19_reg <= icmp_ln620_reg_1109_pp0_iter18_reg;
        icmp_ln620_reg_1109_pp0_iter20_reg <= icmp_ln620_reg_1109_pp0_iter19_reg;
        icmp_ln620_reg_1109_pp0_iter2_reg <= icmp_ln620_reg_1109_pp0_iter1_reg;
        icmp_ln620_reg_1109_pp0_iter3_reg <= icmp_ln620_reg_1109_pp0_iter2_reg;
        icmp_ln620_reg_1109_pp0_iter4_reg <= icmp_ln620_reg_1109_pp0_iter3_reg;
        icmp_ln620_reg_1109_pp0_iter5_reg <= icmp_ln620_reg_1109_pp0_iter4_reg;
        icmp_ln620_reg_1109_pp0_iter6_reg <= icmp_ln620_reg_1109_pp0_iter5_reg;
        icmp_ln620_reg_1109_pp0_iter7_reg <= icmp_ln620_reg_1109_pp0_iter6_reg;
        icmp_ln620_reg_1109_pp0_iter8_reg <= icmp_ln620_reg_1109_pp0_iter7_reg;
        icmp_ln620_reg_1109_pp0_iter9_reg <= icmp_ln620_reg_1109_pp0_iter8_reg;
        icmp_ln655_reg_1113_pp0_iter10_reg <= icmp_ln655_reg_1113_pp0_iter9_reg;
        icmp_ln655_reg_1113_pp0_iter11_reg <= icmp_ln655_reg_1113_pp0_iter10_reg;
        icmp_ln655_reg_1113_pp0_iter12_reg <= icmp_ln655_reg_1113_pp0_iter11_reg;
        icmp_ln655_reg_1113_pp0_iter13_reg <= icmp_ln655_reg_1113_pp0_iter12_reg;
        icmp_ln655_reg_1113_pp0_iter14_reg <= icmp_ln655_reg_1113_pp0_iter13_reg;
        icmp_ln655_reg_1113_pp0_iter15_reg <= icmp_ln655_reg_1113_pp0_iter14_reg;
        icmp_ln655_reg_1113_pp0_iter16_reg <= icmp_ln655_reg_1113_pp0_iter15_reg;
        icmp_ln655_reg_1113_pp0_iter17_reg <= icmp_ln655_reg_1113_pp0_iter16_reg;
        icmp_ln655_reg_1113_pp0_iter18_reg <= icmp_ln655_reg_1113_pp0_iter17_reg;
        icmp_ln655_reg_1113_pp0_iter19_reg <= icmp_ln655_reg_1113_pp0_iter18_reg;
        icmp_ln655_reg_1113_pp0_iter20_reg <= icmp_ln655_reg_1113_pp0_iter19_reg;
        icmp_ln655_reg_1113_pp0_iter21_reg <= icmp_ln655_reg_1113_pp0_iter20_reg;
        icmp_ln655_reg_1113_pp0_iter2_reg <= icmp_ln655_reg_1113_pp0_iter1_reg;
        icmp_ln655_reg_1113_pp0_iter3_reg <= icmp_ln655_reg_1113_pp0_iter2_reg;
        icmp_ln655_reg_1113_pp0_iter4_reg <= icmp_ln655_reg_1113_pp0_iter3_reg;
        icmp_ln655_reg_1113_pp0_iter5_reg <= icmp_ln655_reg_1113_pp0_iter4_reg;
        icmp_ln655_reg_1113_pp0_iter6_reg <= icmp_ln655_reg_1113_pp0_iter5_reg;
        icmp_ln655_reg_1113_pp0_iter7_reg <= icmp_ln655_reg_1113_pp0_iter6_reg;
        icmp_ln655_reg_1113_pp0_iter8_reg <= icmp_ln655_reg_1113_pp0_iter7_reg;
        icmp_ln655_reg_1113_pp0_iter9_reg <= icmp_ln655_reg_1113_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln620_reg_1109 <= icmp_ln620_fu_688_p2;
        icmp_ln620_reg_1109_pp0_iter1_reg <= icmp_ln620_reg_1109;
        icmp_ln636_reg_1105 <= icmp_ln636_fu_666_p2;
        icmp_ln655_reg_1113 <= icmp_ln655_fu_700_p2;
        icmp_ln655_reg_1113_pp0_iter1_reg <= icmp_ln655_reg_1113;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln620_fu_688_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter21_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_block_1 = 27'd0;
    end else begin
        ap_sig_allocacmp_block_1 = block_fu_234;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp69))) begin
        grp_aes_return_fu_556_ap_ce = 1'b1;
    end else begin
        grp_aes_return_fu_556_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp67))) begin
        grp_deAes_return_fu_446_ap_ce = 1'b1;
    end else begin
        grp_deAes_return_fu_446_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln620_reg_1109 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        input_stream_TDATA_blk_n = input_stream_TVALID;
    end else begin
        input_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln620_reg_1109 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_stream_TREADY = 1'b1;
    end else begin
        input_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_stream_TVALID = 1'b1;
    end else begin
        output_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp67 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22_ignore_call0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_ignore_call0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp69 = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22_ignore_call0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_ignore_call0)));
end

assign ap_block_pp0_stage0_ignoreCallOp100 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp103 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp104 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp107 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp108 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp67 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp69 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp71 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp72 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp75 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp76 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp79 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp80 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp83 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp84 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp87 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp88 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp91 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp92 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp95 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp96 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp99 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b1 == ap_block_state23_pp0_stage0_iter22)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state23_pp0_stage0_iter22 = (output_stream_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state23_pp0_stage0_iter22_ignore_call0 = (output_stream_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln620_reg_1109 == 1'd1) & (input_stream_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call0 = ((icmp_ln620_reg_1109 == 1'd1) & (input_stream_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter21_block_data_0_reg_436 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_10_0_reg_336 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_11_0_reg_326 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_12_0_reg_316 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_13_0_reg_306 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_14_0_reg_296 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_15_0_reg_286 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_1_0_reg_426 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_2_0_reg_416 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_3_0_reg_406 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_4_0_reg_396 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_5_0_reg_386 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_6_0_reg_376 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_7_0_reg_366 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_8_0_reg_356 = 'bx;

assign ap_phi_reg_pp0_iter21_block_data_9_0_reg_346 = 'bx;

always @ (*) begin
    ap_predicate_op100_call_state17 = ((icmp_ln620_reg_1109_pp0_iter15_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op103_call_state19 = ((icmp_ln620_reg_1109_pp0_iter17_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op104_call_state19 = ((icmp_ln620_reg_1109_pp0_iter17_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op107_call_state21 = ((icmp_ln620_reg_1109_pp0_iter19_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op108_call_state21 = ((icmp_ln620_reg_1109_pp0_iter19_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op67_call_state2 = ((icmp_ln620_reg_1109 == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op69_call_state2 = ((icmp_ln620_reg_1109 == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op71_call_state3 = ((icmp_ln620_reg_1109_pp0_iter1_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op72_call_state3 = ((icmp_ln620_reg_1109_pp0_iter1_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op75_call_state5 = ((icmp_ln620_reg_1109_pp0_iter3_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op76_call_state5 = ((icmp_ln620_reg_1109_pp0_iter3_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op79_call_state7 = ((icmp_ln620_reg_1109_pp0_iter5_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op80_call_state7 = ((icmp_ln620_reg_1109_pp0_iter5_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op83_call_state9 = ((icmp_ln620_reg_1109_pp0_iter7_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op84_call_state9 = ((icmp_ln620_reg_1109_pp0_iter7_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op87_call_state11 = ((icmp_ln620_reg_1109_pp0_iter9_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op88_call_state11 = ((icmp_ln620_reg_1109_pp0_iter9_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op91_call_state13 = ((icmp_ln620_reg_1109_pp0_iter11_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op92_call_state13 = ((icmp_ln620_reg_1109_pp0_iter11_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op95_call_state15 = ((icmp_ln620_reg_1109_pp0_iter13_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

always @ (*) begin
    ap_predicate_op96_call_state15 = ((icmp_ln620_reg_1109_pp0_iter13_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd1));
end

always @ (*) begin
    ap_predicate_op99_call_state17 = ((icmp_ln620_reg_1109_pp0_iter15_reg == 1'd1) & (icmp_ln636_reg_1105 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign block_2_fu_694_p2 = (ap_sig_allocacmp_block_1 + 27'd1);

assign block_data_fu_715_p1 = input_stream_TDATA[7:0];

assign grp_aes_return_fu_556_p_10_read = {{input_stream_TDATA[87:80]}};

assign grp_aes_return_fu_556_p_11_read = {{input_stream_TDATA[95:88]}};

assign grp_aes_return_fu_556_p_1213_read = {{input_stream_TDATA[103:96]}};

assign grp_aes_return_fu_556_p_13_read = {{input_stream_TDATA[111:104]}};

assign grp_aes_return_fu_556_p_14_read = {{input_stream_TDATA[119:112]}};

assign grp_aes_return_fu_556_p_15_read = {{input_stream_TDATA[127:120]}};

assign grp_aes_return_fu_556_p_1_read = {{input_stream_TDATA[15:8]}};

assign grp_aes_return_fu_556_p_2_read = {{input_stream_TDATA[23:16]}};

assign grp_aes_return_fu_556_p_3_read = {{input_stream_TDATA[31:24]}};

assign grp_aes_return_fu_556_p_4_read = {{input_stream_TDATA[39:32]}};

assign grp_aes_return_fu_556_p_5_read = {{input_stream_TDATA[47:40]}};

assign grp_aes_return_fu_556_p_6_read = {{input_stream_TDATA[55:48]}};

assign grp_aes_return_fu_556_p_7_read = {{input_stream_TDATA[63:56]}};

assign grp_aes_return_fu_556_p_8_read = {{input_stream_TDATA[71:64]}};

assign grp_aes_return_fu_556_p_9_read = {{input_stream_TDATA[79:72]}};

assign grp_deAes_return_fu_446_c_10_read = {{input_stream_TDATA[87:80]}};

assign grp_deAes_return_fu_446_c_11_read = {{input_stream_TDATA[95:88]}};

assign grp_deAes_return_fu_446_c_1213_read = {{input_stream_TDATA[103:96]}};

assign grp_deAes_return_fu_446_c_13_read = {{input_stream_TDATA[111:104]}};

assign grp_deAes_return_fu_446_c_14_read = {{input_stream_TDATA[119:112]}};

assign grp_deAes_return_fu_446_c_15_read = {{input_stream_TDATA[127:120]}};

assign grp_deAes_return_fu_446_c_1_read = {{input_stream_TDATA[15:8]}};

assign grp_deAes_return_fu_446_c_2_read = {{input_stream_TDATA[23:16]}};

assign grp_deAes_return_fu_446_c_3_read = {{input_stream_TDATA[31:24]}};

assign grp_deAes_return_fu_446_c_4_read = {{input_stream_TDATA[39:32]}};

assign grp_deAes_return_fu_446_c_5_read = {{input_stream_TDATA[47:40]}};

assign grp_deAes_return_fu_446_c_6_read = {{input_stream_TDATA[55:48]}};

assign grp_deAes_return_fu_446_c_7_read = {{input_stream_TDATA[63:56]}};

assign grp_deAes_return_fu_446_c_8_read = {{input_stream_TDATA[71:64]}};

assign grp_deAes_return_fu_446_c_9_read = {{input_stream_TDATA[79:72]}};

assign icmp_ln620_fu_688_p2 = (($signed(zext_ln620_1_fu_684_p1) < $signed(num_blocks)) ? 1'b1 : 1'b0);

assign icmp_ln636_fu_666_p2 = ((En_Decryption == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln655_fu_700_p2 = ((zext_ln620_fu_680_p1 == add_ln655) ? 1'b1 : 1'b0);

assign output_stream_TDATA = {{{{{{{{{{{{{{{{block_data_15_0_reg_286}, {block_data_14_0_reg_296}}, {block_data_13_0_reg_306}}, {block_data_12_0_reg_316}}, {block_data_11_0_reg_326}}, {block_data_10_0_reg_336}}, {block_data_9_0_reg_346}}, {block_data_8_0_reg_356}}, {block_data_7_0_reg_366}}, {block_data_6_0_reg_376}}, {block_data_5_0_reg_386}}, {block_data_4_0_reg_396}}, {block_data_3_0_reg_406}}, {block_data_2_0_reg_416}}, {block_data_1_0_reg_426}}, {block_data_0_reg_436}};

assign output_stream_TKEEP = 16'd65535;

assign output_stream_TLAST = icmp_ln655_reg_1113_pp0_iter21_reg;

assign output_stream_TSTRB = 16'd65535;

assign zext_ln620_1_fu_684_p1 = ap_sig_allocacmp_block_1;

assign zext_ln620_fu_680_p1 = ap_sig_allocacmp_block_1;

endmodule //AES_En_De_AES_En_De_Pipeline_VITIS_LOOP_620_2
