// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="AES_En_De_AES_En_De,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.294000,HLS_SYN_LAT=67108940,HLS_SYN_TPT=none,HLS_SYN_MEM=162,HLS_SYN_DSP=0,HLS_SYN_FF=21192,HLS_SYN_LUT=56706,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module AES_En_De (
        ap_clk,
        ap_rst_n,
        input_stream_TDATA,
        input_stream_TVALID,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TLAST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [127:0] input_stream_TDATA;
input   input_stream_TVALID;
output   input_stream_TREADY;
input  [15:0] input_stream_TKEEP;
input  [15:0] input_stream_TSTRB;
input  [0:0] input_stream_TLAST;
output  [127:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [15:0] output_stream_TKEEP;
output  [15:0] output_stream_TSTRB;
output  [0:0] output_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] in_char_len_q0;
reg   [3:0] key_address0;
reg    key_ce0;
wire   [7:0] key_q0;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_9;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_8;
reg   [31:0] w_0;
reg   [31:0] w_1;
reg   [31:0] w_2;
reg   [31:0] w_3;
reg   [31:0] w_4;
reg   [31:0] w_5;
reg   [31:0] w_6;
reg   [31:0] w_7;
reg   [31:0] w_8;
reg   [31:0] w_9;
reg   [31:0] w_10;
reg   [31:0] w_11;
reg   [31:0] w_12;
reg   [31:0] w_13;
reg   [31:0] w_14;
reg   [31:0] w_15;
reg   [31:0] w_16;
reg   [31:0] w_17;
reg   [31:0] w_18;
reg   [31:0] w_19;
reg   [31:0] w_20;
reg   [31:0] w_21;
reg   [31:0] w_22;
reg   [31:0] w_23;
reg   [31:0] w_24;
reg   [31:0] w_25;
reg   [31:0] w_26;
reg   [31:0] w_27;
reg   [31:0] w_28;
reg   [31:0] w_29;
reg   [31:0] w_30;
reg   [31:0] w_31;
reg   [31:0] w_32;
reg   [31:0] w_33;
reg   [31:0] w_34;
reg   [31:0] w_35;
reg   [31:0] w_36;
reg   [31:0] w_37;
reg   [31:0] w_38;
reg   [31:0] w_39;
reg   [31:0] w_40;
reg   [31:0] w_41;
reg   [31:0] w_42;
reg   [31:0] w_43;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_7;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_6;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_5;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_4;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_3;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_2;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key_1;
reg   [7:0] AES_En_De_stream_stream_axis_0_int_char_temp_key;
reg   [7:0] p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_5;
reg   [7:0] p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_4;
reg   [7:0] p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_3;
reg   [7:0] p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_2;
reg   [7:0] p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_1;
reg   [7:0] p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE;
wire    ap_CS_fsm_state2;
wire  signed [27:0] num_blocks_fu_874_p3;
reg   [27:0] num_blocks_reg_1157;
reg   [31:0] En_Decryption_reg_1163;
wire    ap_CS_fsm_state3;
wire  signed [28:0] sext_ln600_fu_882_p1;
reg  signed [28:0] sext_ln600_reg_1178;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire   [28:0] add_ln655_fu_1141_p2;
reg   [28:0] add_ln655_reg_1306;
wire    ap_CS_fsm_state22;
wire    grp_extendKey_fu_621_ap_start;
wire    grp_extendKey_fu_621_ap_done;
wire    grp_extendKey_fu_621_ap_idle;
wire    grp_extendKey_fu_621_ap_ready;
wire   [3:0] grp_extendKey_fu_621_key_address0;
wire    grp_extendKey_fu_621_key_ce0;
wire   [31:0] grp_extendKey_fu_621_w_0_o;
wire    grp_extendKey_fu_621_w_0_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_1_o;
wire    grp_extendKey_fu_621_w_1_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_2_o;
wire    grp_extendKey_fu_621_w_2_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_3_o;
wire    grp_extendKey_fu_621_w_3_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_4_o;
wire    grp_extendKey_fu_621_w_4_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_5_o;
wire    grp_extendKey_fu_621_w_5_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_6_o;
wire    grp_extendKey_fu_621_w_6_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_7_o;
wire    grp_extendKey_fu_621_w_7_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_8_o;
wire    grp_extendKey_fu_621_w_8_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_9_o;
wire    grp_extendKey_fu_621_w_9_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_10_o;
wire    grp_extendKey_fu_621_w_10_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_11_o;
wire    grp_extendKey_fu_621_w_11_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_12_o;
wire    grp_extendKey_fu_621_w_12_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_13_o;
wire    grp_extendKey_fu_621_w_13_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_14_o;
wire    grp_extendKey_fu_621_w_14_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_15_o;
wire    grp_extendKey_fu_621_w_15_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_16_o;
wire    grp_extendKey_fu_621_w_16_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_17_o;
wire    grp_extendKey_fu_621_w_17_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_18_o;
wire    grp_extendKey_fu_621_w_18_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_19_o;
wire    grp_extendKey_fu_621_w_19_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_20_o;
wire    grp_extendKey_fu_621_w_20_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_21_o;
wire    grp_extendKey_fu_621_w_21_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_22_o;
wire    grp_extendKey_fu_621_w_22_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_23_o;
wire    grp_extendKey_fu_621_w_23_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_24_o;
wire    grp_extendKey_fu_621_w_24_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_25_o;
wire    grp_extendKey_fu_621_w_25_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_26_o;
wire    grp_extendKey_fu_621_w_26_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_27_o;
wire    grp_extendKey_fu_621_w_27_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_28_o;
wire    grp_extendKey_fu_621_w_28_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_29_o;
wire    grp_extendKey_fu_621_w_29_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_30_o;
wire    grp_extendKey_fu_621_w_30_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_31_o;
wire    grp_extendKey_fu_621_w_31_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_32_o;
wire    grp_extendKey_fu_621_w_32_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_33_o;
wire    grp_extendKey_fu_621_w_33_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_34_o;
wire    grp_extendKey_fu_621_w_34_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_35_o;
wire    grp_extendKey_fu_621_w_35_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_36_o;
wire    grp_extendKey_fu_621_w_36_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_37_o;
wire    grp_extendKey_fu_621_w_37_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_38_o;
wire    grp_extendKey_fu_621_w_38_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_39_o;
wire    grp_extendKey_fu_621_w_39_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_40_o;
wire    grp_extendKey_fu_621_w_40_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_41_o;
wire    grp_extendKey_fu_621_w_41_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_42_o;
wire    grp_extendKey_fu_621_w_42_o_ap_vld;
wire   [31:0] grp_extendKey_fu_621_w_43;
wire    grp_extendKey_fu_621_w_43_ap_vld;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_done;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_idle;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_ready;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TREADY;
wire   [127:0] grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TDATA;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID;
wire   [15:0] grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TKEEP;
wire   [15:0] grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TSTRB;
wire   [0:0] grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TLAST;
wire    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_input_stream_TREADY;
reg   [0:0] key_change_flag_reg_426;
wire   [0:0] icmp_ln609_fu_889_p2;
reg   [0:0] key_change_flag_1_reg_440;
wire   [0:0] icmp_ln609_1_fu_905_p2;
reg   [0:0] key_change_flag_2_reg_453;
wire   [0:0] icmp_ln609_2_fu_921_p2;
reg   [0:0] key_change_flag_3_reg_466;
wire   [0:0] icmp_ln609_3_fu_937_p2;
reg   [0:0] key_change_flag_4_reg_479;
wire   [0:0] icmp_ln609_4_fu_953_p2;
reg   [0:0] key_change_flag_5_reg_492;
wire   [0:0] icmp_ln609_5_fu_969_p2;
reg   [0:0] key_change_flag_6_reg_505;
wire   [0:0] icmp_ln609_6_fu_985_p2;
reg   [0:0] key_change_flag_7_reg_518;
wire   [0:0] icmp_ln609_7_fu_1001_p2;
reg   [0:0] key_change_flag_8_reg_531;
wire   [0:0] icmp_ln609_8_fu_1017_p2;
reg   [0:0] key_change_flag_9_reg_544;
wire   [0:0] icmp_ln609_9_fu_1033_p2;
reg   [0:0] key_change_flag_10_reg_557;
wire   [0:0] icmp_ln609_10_fu_1049_p2;
reg   [0:0] key_change_flag_11_reg_570;
wire   [0:0] icmp_ln609_11_fu_1065_p2;
reg   [0:0] key_change_flag_12_reg_583;
wire   [0:0] icmp_ln609_12_fu_1081_p2;
reg   [0:0] key_change_flag_13_reg_596;
wire   [0:0] icmp_ln609_13_fu_1097_p2;
wire   [0:0] ap_phi_mux_key_change_flag_14_phi_fu_613_p4;
reg   [0:0] key_change_flag_14_reg_609;
wire   [0:0] icmp_ln609_14_fu_1113_p2;
reg    grp_extendKey_fu_621_ap_start_reg;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg    grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start_reg;
wire    ap_CS_fsm_state23;
reg   [127:0] output_stream_TDATA_reg;
reg   [15:0] output_stream_TKEEP_reg;
reg   [15:0] output_stream_TSTRB_reg;
reg   [0:0] output_stream_TLAST_reg;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln609_15_fu_1129_p2;
reg    in_char_len_ce0_local;
reg   [1:0] in_char_len_address0_local;
reg    in_char_len_we0_local;
reg    key_ce0_local;
reg   [3:0] key_address0_local;
wire   [31:0] sub_ln600_fu_842_p2;
wire   [27:0] tmp_fu_848_p4;
wire   [0:0] tmp_1380_fu_834_p3;
wire   [27:0] sub_ln600_1_fu_858_p2;
wire   [27:0] tmp_s_fu_864_p4;
wire    ap_CS_fsm_state24;
wire    regslice_both_output_stream_V_data_V_U_apdone_blk;
reg   [23:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    regslice_both_input_stream_V_data_V_U_apdone_blk;
wire   [127:0] input_stream_TDATA_int_regslice;
wire    input_stream_TVALID_int_regslice;
reg    input_stream_TREADY_int_regslice;
wire    regslice_both_input_stream_V_data_V_U_ack_in;
wire    regslice_both_input_stream_V_keep_V_U_apdone_blk;
wire   [15:0] input_stream_TKEEP_int_regslice;
wire    regslice_both_input_stream_V_keep_V_U_vld_out;
wire    regslice_both_input_stream_V_keep_V_U_ack_in;
wire    regslice_both_input_stream_V_strb_V_U_apdone_blk;
wire   [15:0] input_stream_TSTRB_int_regslice;
wire    regslice_both_input_stream_V_strb_V_U_vld_out;
wire    regslice_both_input_stream_V_strb_V_U_ack_in;
wire    regslice_both_input_stream_V_last_V_U_apdone_blk;
wire   [0:0] input_stream_TLAST_int_regslice;
wire    regslice_both_input_stream_V_last_V_U_vld_out;
wire    regslice_both_input_stream_V_last_V_U_ack_in;
reg   [127:0] output_stream_TDATA_int_regslice;
wire    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_V_data_V_U_vld_out;
wire    regslice_both_output_stream_V_keep_V_U_apdone_blk;
reg   [15:0] output_stream_TKEEP_int_regslice;
wire    regslice_both_output_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_keep_V_U_vld_out;
wire    regslice_both_output_stream_V_strb_V_U_apdone_blk;
reg   [15:0] output_stream_TSTRB_int_regslice;
wire    regslice_both_output_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_strb_V_U_vld_out;
wire    regslice_both_output_stream_V_last_V_U_apdone_blk;
reg   [0:0] output_stream_TLAST_int_regslice;
wire    regslice_both_output_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_9 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_8 = 8'd0;
#0 w_0 = 32'd0;
#0 w_1 = 32'd0;
#0 w_2 = 32'd0;
#0 w_3 = 32'd0;
#0 w_4 = 32'd0;
#0 w_5 = 32'd0;
#0 w_6 = 32'd0;
#0 w_7 = 32'd0;
#0 w_8 = 32'd0;
#0 w_9 = 32'd0;
#0 w_10 = 32'd0;
#0 w_11 = 32'd0;
#0 w_12 = 32'd0;
#0 w_13 = 32'd0;
#0 w_14 = 32'd0;
#0 w_15 = 32'd0;
#0 w_16 = 32'd0;
#0 w_17 = 32'd0;
#0 w_18 = 32'd0;
#0 w_19 = 32'd0;
#0 w_20 = 32'd0;
#0 w_21 = 32'd0;
#0 w_22 = 32'd0;
#0 w_23 = 32'd0;
#0 w_24 = 32'd0;
#0 w_25 = 32'd0;
#0 w_26 = 32'd0;
#0 w_27 = 32'd0;
#0 w_28 = 32'd0;
#0 w_29 = 32'd0;
#0 w_30 = 32'd0;
#0 w_31 = 32'd0;
#0 w_32 = 32'd0;
#0 w_33 = 32'd0;
#0 w_34 = 32'd0;
#0 w_35 = 32'd0;
#0 w_36 = 32'd0;
#0 w_37 = 32'd0;
#0 w_38 = 32'd0;
#0 w_39 = 32'd0;
#0 w_40 = 32'd0;
#0 w_41 = 32'd0;
#0 w_42 = 32'd0;
#0 w_43 = 32'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_7 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_6 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_5 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_4 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_3 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_2 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key_1 = 8'd0;
#0 AES_En_De_stream_stream_axis_0_int_char_temp_key = 8'd0;
#0 p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_5 = 8'd0;
#0 p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_4 = 8'd0;
#0 p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_3 = 8'd0;
#0 p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_2 = 8'd0;
#0 p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_1 = 8'd0;
#0 p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE = 8'd0;
#0 grp_extendKey_fu_621_ap_start_reg = 1'b0;
#0 grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start_reg = 1'b0;
end

AES_En_De_extendKey grp_extendKey_fu_621(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_extendKey_fu_621_ap_start),
    .ap_done(grp_extendKey_fu_621_ap_done),
    .ap_idle(grp_extendKey_fu_621_ap_idle),
    .ap_ready(grp_extendKey_fu_621_ap_ready),
    .key_address0(grp_extendKey_fu_621_key_address0),
    .key_ce0(grp_extendKey_fu_621_key_ce0),
    .key_q0(key_q0),
    .w_0_i(w_0),
    .w_0_o(grp_extendKey_fu_621_w_0_o),
    .w_0_o_ap_vld(grp_extendKey_fu_621_w_0_o_ap_vld),
    .w_1_i(w_1),
    .w_1_o(grp_extendKey_fu_621_w_1_o),
    .w_1_o_ap_vld(grp_extendKey_fu_621_w_1_o_ap_vld),
    .w_2_i(w_2),
    .w_2_o(grp_extendKey_fu_621_w_2_o),
    .w_2_o_ap_vld(grp_extendKey_fu_621_w_2_o_ap_vld),
    .w_3_i(w_3),
    .w_3_o(grp_extendKey_fu_621_w_3_o),
    .w_3_o_ap_vld(grp_extendKey_fu_621_w_3_o_ap_vld),
    .w_4_i(w_4),
    .w_4_o(grp_extendKey_fu_621_w_4_o),
    .w_4_o_ap_vld(grp_extendKey_fu_621_w_4_o_ap_vld),
    .w_5_i(w_5),
    .w_5_o(grp_extendKey_fu_621_w_5_o),
    .w_5_o_ap_vld(grp_extendKey_fu_621_w_5_o_ap_vld),
    .w_6_i(w_6),
    .w_6_o(grp_extendKey_fu_621_w_6_o),
    .w_6_o_ap_vld(grp_extendKey_fu_621_w_6_o_ap_vld),
    .w_7_i(w_7),
    .w_7_o(grp_extendKey_fu_621_w_7_o),
    .w_7_o_ap_vld(grp_extendKey_fu_621_w_7_o_ap_vld),
    .w_8_i(w_8),
    .w_8_o(grp_extendKey_fu_621_w_8_o),
    .w_8_o_ap_vld(grp_extendKey_fu_621_w_8_o_ap_vld),
    .w_9_i(w_9),
    .w_9_o(grp_extendKey_fu_621_w_9_o),
    .w_9_o_ap_vld(grp_extendKey_fu_621_w_9_o_ap_vld),
    .w_10_i(w_10),
    .w_10_o(grp_extendKey_fu_621_w_10_o),
    .w_10_o_ap_vld(grp_extendKey_fu_621_w_10_o_ap_vld),
    .w_11_i(w_11),
    .w_11_o(grp_extendKey_fu_621_w_11_o),
    .w_11_o_ap_vld(grp_extendKey_fu_621_w_11_o_ap_vld),
    .w_12_i(w_12),
    .w_12_o(grp_extendKey_fu_621_w_12_o),
    .w_12_o_ap_vld(grp_extendKey_fu_621_w_12_o_ap_vld),
    .w_13_i(w_13),
    .w_13_o(grp_extendKey_fu_621_w_13_o),
    .w_13_o_ap_vld(grp_extendKey_fu_621_w_13_o_ap_vld),
    .w_14_i(w_14),
    .w_14_o(grp_extendKey_fu_621_w_14_o),
    .w_14_o_ap_vld(grp_extendKey_fu_621_w_14_o_ap_vld),
    .w_15_i(w_15),
    .w_15_o(grp_extendKey_fu_621_w_15_o),
    .w_15_o_ap_vld(grp_extendKey_fu_621_w_15_o_ap_vld),
    .w_16_i(w_16),
    .w_16_o(grp_extendKey_fu_621_w_16_o),
    .w_16_o_ap_vld(grp_extendKey_fu_621_w_16_o_ap_vld),
    .w_17_i(w_17),
    .w_17_o(grp_extendKey_fu_621_w_17_o),
    .w_17_o_ap_vld(grp_extendKey_fu_621_w_17_o_ap_vld),
    .w_18_i(w_18),
    .w_18_o(grp_extendKey_fu_621_w_18_o),
    .w_18_o_ap_vld(grp_extendKey_fu_621_w_18_o_ap_vld),
    .w_19_i(w_19),
    .w_19_o(grp_extendKey_fu_621_w_19_o),
    .w_19_o_ap_vld(grp_extendKey_fu_621_w_19_o_ap_vld),
    .w_20_i(w_20),
    .w_20_o(grp_extendKey_fu_621_w_20_o),
    .w_20_o_ap_vld(grp_extendKey_fu_621_w_20_o_ap_vld),
    .w_21_i(w_21),
    .w_21_o(grp_extendKey_fu_621_w_21_o),
    .w_21_o_ap_vld(grp_extendKey_fu_621_w_21_o_ap_vld),
    .w_22_i(w_22),
    .w_22_o(grp_extendKey_fu_621_w_22_o),
    .w_22_o_ap_vld(grp_extendKey_fu_621_w_22_o_ap_vld),
    .w_23_i(w_23),
    .w_23_o(grp_extendKey_fu_621_w_23_o),
    .w_23_o_ap_vld(grp_extendKey_fu_621_w_23_o_ap_vld),
    .w_24_i(w_24),
    .w_24_o(grp_extendKey_fu_621_w_24_o),
    .w_24_o_ap_vld(grp_extendKey_fu_621_w_24_o_ap_vld),
    .w_25_i(w_25),
    .w_25_o(grp_extendKey_fu_621_w_25_o),
    .w_25_o_ap_vld(grp_extendKey_fu_621_w_25_o_ap_vld),
    .w_26_i(w_26),
    .w_26_o(grp_extendKey_fu_621_w_26_o),
    .w_26_o_ap_vld(grp_extendKey_fu_621_w_26_o_ap_vld),
    .w_27_i(w_27),
    .w_27_o(grp_extendKey_fu_621_w_27_o),
    .w_27_o_ap_vld(grp_extendKey_fu_621_w_27_o_ap_vld),
    .w_28_i(w_28),
    .w_28_o(grp_extendKey_fu_621_w_28_o),
    .w_28_o_ap_vld(grp_extendKey_fu_621_w_28_o_ap_vld),
    .w_29_i(w_29),
    .w_29_o(grp_extendKey_fu_621_w_29_o),
    .w_29_o_ap_vld(grp_extendKey_fu_621_w_29_o_ap_vld),
    .w_30_i(w_30),
    .w_30_o(grp_extendKey_fu_621_w_30_o),
    .w_30_o_ap_vld(grp_extendKey_fu_621_w_30_o_ap_vld),
    .w_31_i(w_31),
    .w_31_o(grp_extendKey_fu_621_w_31_o),
    .w_31_o_ap_vld(grp_extendKey_fu_621_w_31_o_ap_vld),
    .w_32_i(w_32),
    .w_32_o(grp_extendKey_fu_621_w_32_o),
    .w_32_o_ap_vld(grp_extendKey_fu_621_w_32_o_ap_vld),
    .w_33_i(w_33),
    .w_33_o(grp_extendKey_fu_621_w_33_o),
    .w_33_o_ap_vld(grp_extendKey_fu_621_w_33_o_ap_vld),
    .w_34_i(w_34),
    .w_34_o(grp_extendKey_fu_621_w_34_o),
    .w_34_o_ap_vld(grp_extendKey_fu_621_w_34_o_ap_vld),
    .w_35_i(w_35),
    .w_35_o(grp_extendKey_fu_621_w_35_o),
    .w_35_o_ap_vld(grp_extendKey_fu_621_w_35_o_ap_vld),
    .w_36_i(w_36),
    .w_36_o(grp_extendKey_fu_621_w_36_o),
    .w_36_o_ap_vld(grp_extendKey_fu_621_w_36_o_ap_vld),
    .w_37_i(w_37),
    .w_37_o(grp_extendKey_fu_621_w_37_o),
    .w_37_o_ap_vld(grp_extendKey_fu_621_w_37_o_ap_vld),
    .w_38_i(w_38),
    .w_38_o(grp_extendKey_fu_621_w_38_o),
    .w_38_o_ap_vld(grp_extendKey_fu_621_w_38_o_ap_vld),
    .w_39_i(w_39),
    .w_39_o(grp_extendKey_fu_621_w_39_o),
    .w_39_o_ap_vld(grp_extendKey_fu_621_w_39_o_ap_vld),
    .w_40_i(w_40),
    .w_40_o(grp_extendKey_fu_621_w_40_o),
    .w_40_o_ap_vld(grp_extendKey_fu_621_w_40_o_ap_vld),
    .w_41_i(w_41),
    .w_41_o(grp_extendKey_fu_621_w_41_o),
    .w_41_o_ap_vld(grp_extendKey_fu_621_w_41_o_ap_vld),
    .w_42_i(w_42),
    .w_42_o(grp_extendKey_fu_621_w_42_o),
    .w_42_o_ap_vld(grp_extendKey_fu_621_w_42_o_ap_vld),
    .w_43(grp_extendKey_fu_621_w_43),
    .w_43_ap_vld(grp_extendKey_fu_621_w_43_ap_vld)
);

AES_En_De_AES_En_De_Pipeline_VITIS_LOOP_620_2 grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start),
    .ap_done(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_done),
    .ap_idle(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_idle),
    .ap_ready(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_ready),
    .input_stream_TVALID(input_stream_TVALID_int_regslice),
    .output_stream_TREADY(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TREADY),
    .En_Decryption(En_Decryption_reg_1163),
    .num_blocks(num_blocks_reg_1157),
    .add_ln655(add_ln655_reg_1306),
    .output_stream_TDATA(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TDATA),
    .output_stream_TVALID(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID),
    .output_stream_TKEEP(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TKEEP),
    .output_stream_TSTRB(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TSTRB),
    .output_stream_TLAST(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TLAST),
    .input_stream_TDATA(input_stream_TDATA_int_regslice),
    .input_stream_TREADY(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP_int_regslice),
    .input_stream_TSTRB(input_stream_TSTRB_int_regslice),
    .input_stream_TLAST(input_stream_TLAST_int_regslice),
    .w_0(w_0),
    .w_1(w_1),
    .w_2(w_2),
    .w_3(w_3),
    .w_4(w_4),
    .w_5(w_5),
    .w_6(w_6),
    .w_7(w_7),
    .w_8(w_8),
    .w_9(w_9),
    .w_10(w_10),
    .w_11(w_11),
    .w_12(w_12),
    .w_13(w_13),
    .w_14(w_14),
    .w_15(w_15),
    .w_16(w_16),
    .w_17(w_17),
    .w_18(w_18),
    .w_19(w_19),
    .w_20(w_20),
    .w_21(w_21),
    .w_22(w_22),
    .w_23(w_23),
    .w_24(w_24),
    .w_25(w_25),
    .w_26(w_26),
    .w_27(w_27),
    .w_28(w_28),
    .w_29(w_29),
    .w_30(w_30),
    .w_31(w_31),
    .w_32(w_32),
    .w_33(w_33),
    .w_34(w_34),
    .w_35(w_35),
    .w_36(w_36),
    .w_37(w_37),
    .w_38(w_38),
    .w_39(w_39),
    .w_40(w_40),
    .w_41(w_41),
    .w_42(w_42),
    .w_43(w_43)
);

AES_En_De_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_char_len_address0(in_char_len_address0_local),
    .in_char_len_ce0(in_char_len_ce0_local),
    .in_char_len_we0(in_char_len_we0_local),
    .in_char_len_d0(32'd9),
    .in_char_len_q0(in_char_len_q0),
    .key_address0(key_address0),
    .key_ce0(key_ce0),
    .key_q0(key_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

AES_En_De_regslice_both #(
    .DataWidth( 128 ))
regslice_both_input_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TDATA),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_data_V_U_ack_in),
    .data_out(input_stream_TDATA_int_regslice),
    .vld_out(input_stream_TVALID_int_regslice),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_data_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TKEEP),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_keep_V_U_ack_in),
    .data_out(input_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream_V_keep_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_keep_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TSTRB),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_strb_V_U_ack_in),
    .data_out(input_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream_V_strb_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_strb_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_stream_TLAST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_last_V_U_ack_in),
    .data_out(input_stream_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream_V_last_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_last_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 128 ))
regslice_both_output_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_V_data_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_data_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TKEEP_int_regslice),
    .vld_in(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_keep_V_U_ack_in_dummy),
    .data_out(output_stream_TKEEP),
    .vld_out(regslice_both_output_stream_V_keep_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_keep_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TSTRB_int_regslice),
    .vld_in(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_strb_V_U_ack_in_dummy),
    .data_out(output_stream_TSTRB),
    .vld_out(regslice_both_output_stream_V_strb_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_strb_V_U_apdone_blk)
);

AES_En_De_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_stream_TLAST_int_regslice),
    .vld_in(grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID),
    .ack_in(regslice_both_output_stream_V_last_V_U_ack_in_dummy),
    .data_out(output_stream_TLAST),
    .vld_out(regslice_both_output_stream_V_last_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state22)) begin
            grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start_reg <= 1'b1;
        end else if ((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_ready == 1'b1)) begin
            grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_extendKey_fu_621_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_extendKey_fu_621_ap_start_reg <= 1'b1;
        end else if ((grp_extendKey_fu_621_ap_ready == 1'b1)) begin
            grp_extendKey_fu_621_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        if ((icmp_ln609_10_fu_1049_p2 == 1'd1)) begin
            key_change_flag_10_reg_557 <= key_change_flag_9_reg_544;
        end else if ((icmp_ln609_10_fu_1049_p2 == 1'd0)) begin
            key_change_flag_10_reg_557 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        if ((icmp_ln609_11_fu_1065_p2 == 1'd1)) begin
            key_change_flag_11_reg_570 <= key_change_flag_10_reg_557;
        end else if ((icmp_ln609_11_fu_1065_p2 == 1'd0)) begin
            key_change_flag_11_reg_570 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        if ((icmp_ln609_12_fu_1081_p2 == 1'd1)) begin
            key_change_flag_12_reg_583 <= key_change_flag_11_reg_570;
        end else if ((icmp_ln609_12_fu_1081_p2 == 1'd0)) begin
            key_change_flag_12_reg_583 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        if ((icmp_ln609_13_fu_1097_p2 == 1'd1)) begin
            key_change_flag_13_reg_596 <= key_change_flag_12_reg_583;
        end else if ((icmp_ln609_13_fu_1097_p2 == 1'd0)) begin
            key_change_flag_13_reg_596 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((icmp_ln609_14_fu_1113_p2 == 1'd1)) begin
            key_change_flag_14_reg_609 <= key_change_flag_13_reg_596;
        end else if ((icmp_ln609_14_fu_1113_p2 == 1'd0)) begin
            key_change_flag_14_reg_609 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_ln609_1_fu_905_p2 == 1'd1)) begin
            key_change_flag_1_reg_440 <= key_change_flag_reg_426;
        end else if ((icmp_ln609_1_fu_905_p2 == 1'd0)) begin
            key_change_flag_1_reg_440 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((icmp_ln609_2_fu_921_p2 == 1'd1)) begin
            key_change_flag_2_reg_453 <= key_change_flag_1_reg_440;
        end else if ((icmp_ln609_2_fu_921_p2 == 1'd0)) begin
            key_change_flag_2_reg_453 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((icmp_ln609_3_fu_937_p2 == 1'd1)) begin
            key_change_flag_3_reg_466 <= key_change_flag_2_reg_453;
        end else if ((icmp_ln609_3_fu_937_p2 == 1'd0)) begin
            key_change_flag_3_reg_466 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        if ((icmp_ln609_4_fu_953_p2 == 1'd1)) begin
            key_change_flag_4_reg_479 <= key_change_flag_3_reg_466;
        end else if ((icmp_ln609_4_fu_953_p2 == 1'd0)) begin
            key_change_flag_4_reg_479 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln609_5_fu_969_p2 == 1'd1)) begin
            key_change_flag_5_reg_492 <= key_change_flag_4_reg_479;
        end else if ((icmp_ln609_5_fu_969_p2 == 1'd0)) begin
            key_change_flag_5_reg_492 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        if ((icmp_ln609_6_fu_985_p2 == 1'd1)) begin
            key_change_flag_6_reg_505 <= key_change_flag_5_reg_492;
        end else if ((icmp_ln609_6_fu_985_p2 == 1'd0)) begin
            key_change_flag_6_reg_505 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((icmp_ln609_7_fu_1001_p2 == 1'd1)) begin
            key_change_flag_7_reg_518 <= key_change_flag_6_reg_505;
        end else if ((icmp_ln609_7_fu_1001_p2 == 1'd0)) begin
            key_change_flag_7_reg_518 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        if ((icmp_ln609_8_fu_1017_p2 == 1'd1)) begin
            key_change_flag_8_reg_531 <= key_change_flag_7_reg_518;
        end else if ((icmp_ln609_8_fu_1017_p2 == 1'd0)) begin
            key_change_flag_8_reg_531 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        if ((icmp_ln609_9_fu_1033_p2 == 1'd1)) begin
            key_change_flag_9_reg_544 <= key_change_flag_8_reg_531;
        end else if ((icmp_ln609_9_fu_1033_p2 == 1'd0)) begin
            key_change_flag_9_reg_544 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((icmp_ln609_fu_889_p2 == 1'd1)) begin
            key_change_flag_reg_426 <= 1'd0;
        end else if ((icmp_ln609_fu_889_p2 == 1'd0)) begin
            key_change_flag_reg_426 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_9_fu_1033_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_8_fu_1017_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_1 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_7_fu_1001_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_2 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_6_fu_985_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_3 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_5_fu_969_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_4 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_4_fu_953_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_5 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_3_fu_937_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_6 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_2_fu_921_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_7 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_1_fu_905_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_8 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_fu_889_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        AES_En_De_stream_stream_axis_0_int_char_temp_key_9 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        En_Decryption_reg_1163 <= in_char_len_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        add_ln655_reg_1306 <= add_ln655_fu_1141_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        num_blocks_reg_1157 <= num_blocks_fu_874_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        output_stream_TDATA_reg <= grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TDATA;
        output_stream_TKEEP_reg <= grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TKEEP;
        output_stream_TLAST_reg <= grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TLAST;
        output_stream_TSTRB_reg <= grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_15_fu_1129_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_14_fu_1113_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_1 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_13_fu_1097_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_2 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_12_fu_1081_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_3 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_11_fu_1065_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_4 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln609_10_fu_1049_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_5 <= key_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sext_ln600_reg_1178 <= sext_ln600_fu_882_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_0 <= grp_extendKey_fu_621_w_0_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_1 <= grp_extendKey_fu_621_w_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_10_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_10 <= grp_extendKey_fu_621_w_10_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_11_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_11 <= grp_extendKey_fu_621_w_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_12 <= grp_extendKey_fu_621_w_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_13 <= grp_extendKey_fu_621_w_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_14_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_14 <= grp_extendKey_fu_621_w_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_15_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_15 <= grp_extendKey_fu_621_w_15_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_16_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_16 <= grp_extendKey_fu_621_w_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_17_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_17 <= grp_extendKey_fu_621_w_17_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_18_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_18 <= grp_extendKey_fu_621_w_18_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_19_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_19 <= grp_extendKey_fu_621_w_19_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_2 <= grp_extendKey_fu_621_w_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_20_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_20 <= grp_extendKey_fu_621_w_20_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_21_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_21 <= grp_extendKey_fu_621_w_21_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_22_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_22 <= grp_extendKey_fu_621_w_22_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_23_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_23 <= grp_extendKey_fu_621_w_23_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_24_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_24 <= grp_extendKey_fu_621_w_24_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_25_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_25 <= grp_extendKey_fu_621_w_25_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_26_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_26 <= grp_extendKey_fu_621_w_26_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_27_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_27 <= grp_extendKey_fu_621_w_27_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_28_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_28 <= grp_extendKey_fu_621_w_28_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_29_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_29 <= grp_extendKey_fu_621_w_29_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_3 <= grp_extendKey_fu_621_w_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_30_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_30 <= grp_extendKey_fu_621_w_30_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_31_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_31 <= grp_extendKey_fu_621_w_31_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_32_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_32 <= grp_extendKey_fu_621_w_32_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_33_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_33 <= grp_extendKey_fu_621_w_33_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_34_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_34 <= grp_extendKey_fu_621_w_34_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_35_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_35 <= grp_extendKey_fu_621_w_35_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_36_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_36 <= grp_extendKey_fu_621_w_36_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_37_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_37 <= grp_extendKey_fu_621_w_37_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_38_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_38 <= grp_extendKey_fu_621_w_38_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_39_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_39 <= grp_extendKey_fu_621_w_39_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_4 <= grp_extendKey_fu_621_w_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_40_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_40 <= grp_extendKey_fu_621_w_40_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_41_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_41 <= grp_extendKey_fu_621_w_41_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_42_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_42 <= grp_extendKey_fu_621_w_42_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_43_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_43 <= grp_extendKey_fu_621_w_43;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_5 <= grp_extendKey_fu_621_w_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_6 <= grp_extendKey_fu_621_w_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_7 <= grp_extendKey_fu_621_w_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_8 <= grp_extendKey_fu_621_w_8_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_extendKey_fu_621_w_9_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        w_9 <= grp_extendKey_fu_621_w_9_o;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_extendKey_fu_621_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_char_len_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_char_len_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        in_char_len_address0_local = 64'd0;
    end else begin
        in_char_len_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_char_len_ce0_local = 1'b1;
    end else begin
        in_char_len_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_char_len_we0_local = 1'b1;
    end else begin
        in_char_len_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        input_stream_TREADY_int_regslice = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_input_stream_TREADY;
    end else begin
        input_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        key_address0 = grp_extendKey_fu_621_key_address0;
    end else begin
        key_address0 = key_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        key_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        key_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        key_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        key_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        key_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        key_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        key_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        key_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        key_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        key_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        key_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        key_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        key_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        key_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        key_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        key_address0_local = 64'd0;
    end else begin
        key_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        key_ce0 = grp_extendKey_fu_621_key_ce0;
    end else begin
        key_ce0 = key_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        key_ce0_local = 1'b1;
    end else begin
        key_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        output_stream_TDATA_int_regslice = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TDATA;
    end else begin
        output_stream_TDATA_int_regslice = output_stream_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        output_stream_TKEEP_int_regslice = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TKEEP;
    end else begin
        output_stream_TKEEP_int_regslice = output_stream_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        output_stream_TLAST_int_regslice = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TLAST;
    end else begin
        output_stream_TLAST_int_regslice = output_stream_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        output_stream_TSTRB_int_regslice = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TSTRB;
    end else begin
        output_stream_TSTRB_int_regslice = output_stream_TSTRB_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln609_15_fu_1129_p2 == 1'd1) & (ap_phi_mux_key_change_flag_14_phi_fu_613_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_extendKey_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln655_fu_1141_p2 = ($signed(sext_ln600_reg_1178) + $signed(29'd536870911));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_phi_mux_key_change_flag_14_phi_fu_613_p4 = key_change_flag_14_reg_609;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_ap_start_reg;

assign grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TREADY = (output_stream_TREADY_int_regslice & ap_CS_fsm_state23);

assign grp_extendKey_fu_621_ap_start = grp_extendKey_fu_621_ap_start_reg;

assign icmp_ln609_10_fu_1049_p2 = ((p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_5 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_11_fu_1065_p2 = ((p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_4 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_12_fu_1081_p2 = ((p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_3 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_13_fu_1097_p2 = ((p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_2 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_14_fu_1113_p2 = ((p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE_1 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_15_fu_1129_p2 = ((p_ZZ9AES_En_DeRN3hls6streamINS_4axisI7ap_uintILi128EELm0ELm0ELm0ELh56ELb0EEELi0EE == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_1_fu_905_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_8 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_2_fu_921_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_7 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_3_fu_937_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_6 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_4_fu_953_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_5 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_5_fu_969_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_4 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_6_fu_985_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_3 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_7_fu_1001_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_2 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_8_fu_1017_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_1 == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_9_fu_1033_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key == key_q0) ? 1'b1 : 1'b0);

assign icmp_ln609_fu_889_p2 = ((AES_En_De_stream_stream_axis_0_int_char_temp_key_9 == key_q0) ? 1'b1 : 1'b0);

assign input_stream_TREADY = regslice_both_input_stream_V_data_V_U_ack_in;

assign num_blocks_fu_874_p3 = ((tmp_1380_fu_834_p3[0:0] == 1'b1) ? sub_ln600_1_fu_858_p2 : tmp_s_fu_864_p4);

assign output_stream_TVALID = regslice_both_output_stream_V_data_V_U_vld_out;

assign output_stream_TVALID_int_regslice = grp_AES_En_De_Pipeline_VITIS_LOOP_620_2_fu_719_output_stream_TVALID;

assign sext_ln600_fu_882_p1 = $signed(num_blocks_reg_1157);

assign sub_ln600_1_fu_858_p2 = (28'd0 - tmp_fu_848_p4);

assign sub_ln600_fu_842_p2 = (32'd0 - in_char_len_q0);

assign tmp_1380_fu_834_p3 = in_char_len_q0[32'd31];

assign tmp_fu_848_p4 = {{sub_ln600_fu_842_p2[31:4]}};

assign tmp_s_fu_864_p4 = {{in_char_len_q0[31:4]}};


reg find_kernel_block = 0;
// synthesis translate_off
`include "AES_En_De_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //AES_En_De

