# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/esaik/aes/aes.srcs/sources_1/bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0.xci
# IP: The module: 'aes_axi_interconnect_1_imp_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_axi_interconnect_1_imp_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_axi_interconnect_1_imp_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/esaik/aes/aes.srcs/sources_1/bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0.xci
# IP: The module: 'aes_axi_interconnect_1_imp_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_axi_interconnect_1_imp_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_axi_interconnect_1_imp_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
