# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/esaik/aes/aes.srcs/sources_1/bd/aes/ip/aes_AES_En_De_0_0/aes_AES_En_De_0_0.xci
# IP: The module: 'aes_AES_En_De_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/ip/aes_AES_En_De_0_0/constraints/AES_En_De_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_AES_En_De_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/esaik/aes/aes.srcs/sources_1/bd/aes/ip/aes_AES_En_De_0_0/aes_AES_En_De_0_0.xci
# IP: The module: 'aes_AES_En_De_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/ip/aes_AES_En_De_0_0/constraints/AES_En_De_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes_AES_En_De_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
