# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/aes/aes.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes || ORIG_REF_NAME==aes} -quiet] -quiet

# IP: bd/aes/ip/aes_processing_system7_0_0/aes_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_processing_system7_0_0 || ORIG_REF_NAME==aes_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes/ip/aes_AES_En_De_0_0/aes_AES_En_De_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_AES_En_De_0_0 || ORIG_REF_NAME==aes_AES_En_De_0_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_smc_0/aes_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_smc_0 || ORIG_REF_NAME==aes_axi_smc_0} -quiet] -quiet

# IP: bd/aes/ip/aes_rst_ps7_0_50M_0/aes_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_rst_ps7_0_50M_0 || ORIG_REF_NAME==aes_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_dma_0_0/aes_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_dma_0_0 || ORIG_REF_NAME==aes_axi_dma_0_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_interconnect_0_imp_auto_ds_0/aes_axi_interconnect_0_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_interconnect_0_imp_auto_ds_0 || ORIG_REF_NAME==aes_axi_interconnect_0_imp_auto_ds_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_interconnect_0_imp_auto_pc_0/aes_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==aes_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_interconnect_0_0/aes_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_interconnect_0_0 || ORIG_REF_NAME==aes_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_interconnect_1_imp_auto_ds_0/aes_axi_interconnect_1_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_interconnect_1_imp_auto_ds_0 || ORIG_REF_NAME==aes_axi_interconnect_1_imp_auto_ds_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_interconnect_1_imp_auto_pc_0/aes_axi_interconnect_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_interconnect_1_imp_auto_pc_0 || ORIG_REF_NAME==aes_axi_interconnect_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/aes/ip/aes_axi_interconnect_1_0/aes_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==aes_axi_interconnect_1_0 || ORIG_REF_NAME==aes_axi_interconnect_1_0} -quiet] -quiet

# XDC: c:/Users/esaik/aes/aes.gen/sources_1/bd/aes/aes_ooc.xdc
